# Generated by Django 2.2.7 on 2022-06-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='Owner',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='owner_profile',
            new_name='author_profile',
        ),
    ]
