# Generated by Django 2.2.7 on 2022-06-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardo', '0002_auto_20220614_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='author_profile',
        ),
    ]
