# Generated by Django 2.2.24 on 2022-06-16 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardo', '0003_remove_projects_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
